import type { StationId, LifestylePersonaId, StationCustomOverride } from '../types';
import {
  BookOpen,
  Briefcase,
  Dumbbell,
  Laptop,
  Mic,
  Trophy,
  GraduationCap,
  Scroll,
  HeartHandshake,
  Sparkles,
  Home,
  Palette,
  Brain,
  Compass,
} from 'lucide-react';

export interface StationMetadata {
  id: StationId;
  stepNum: number;
  titleAr: string;
  titleEn: string;
  shortLabelAr: string;
  shortLabelEn: string;
  shortTime: string;
  descriptionAr: string;
  descriptionEn: string;
  icon: any;
}

export interface LifestylePersonaConfig {
  id: LifestylePersonaId;
  titleAr: string;
  titleEn: string;
  subtitleAr: string;
  subtitleEn: string;
  badge: string;
  avatarEmoji: string;
  stations: Record<Exclude<StationId, 'HOME'>, Omit<StationMetadata, 'id' | 'stepNum'>>;
}

export const LIFESTYLE_PERSONAS: Record<LifestylePersonaId, LifestylePersonaConfig> = {
  builder_exec: {
    id: 'builder_exec',
    titleAr: 'رائد الأعمال والمهندس',
    titleEn: 'Builder & Executive',
    subtitleAr: 'للمحترفين، المهندسين، وصُنّاع التقنية الراغبين في حسم المهام الكبرى.',
    subtitleEn: 'For engineers, executives, and builders driving deep work.',
    badge: '⚡ إنتاجية عميقة',
    avatarEmoji: '💼',
    stations: {
      COMMUTE_MORNING: {
        titleAr: 'ورد الصباح والقرآن الكريم',
        titleEn: 'Morning Quran & Commute',
        shortLabelAr: 'القرآن',
        shortLabelEn: 'Quran',
        shortTime: '06:00 - 08:00',
        descriptionAr: 'بركة اليوم، سورة البقرة، وأذكار الصباح.',
        descriptionEn: 'Daily Wird, Al-Baqarah, and morning reflection.',
        icon: BookOpen,
      },
      WORK_MICRO_SPRINT: {
        titleAr: 'جلسات العمل والتركيز العميق',
        titleEn: 'Deep Work Sprints',
        shortLabelAr: 'العمل',
        shortLabelEn: 'Work',
        shortTime: '09:00 - 13:00',
        descriptionAr: 'أشواط تركيز مكثفة ومنتجة بلا مقاطعة.',
        descriptionEn: 'High-leverage focus work blocks.',
        icon: Briefcase,
      },
      ONE_SEC_FRICTION: {
        titleAr: 'كسر التسويف والمقاومة',
        titleEn: 'Anti-Friction Sprint',
        shortLabelAr: 'التسويف',
        shortLabelEn: 'Friction',
        shortTime: 'حسب الحاجة',
        descriptionAr: 'قاعدة الدقيقتين للبدء الفوري.',
        descriptionEn: '2-minute rule to crush resistance.',
        icon: Sparkles,
      },
      SOCIAL_MEDIA_BREAK: {
        titleAr: 'استراحة ذهنية واعية',
        titleEn: 'Mindful Recharge',
        shortLabelAr: 'استراحة',
        shortLabelEn: 'Break',
        shortTime: '15 دقيقة',
        descriptionAr: 'استعادة الصفاء وفصل التشتت.',
        descriptionEn: 'Disconnect and restore mental clarity.',
        icon: Brain,
      },
      GYM_ANCHOR: {
        titleAr: 'مرساة القوة والرياضة',
        titleEn: 'Gym Anchor',
        shortLabelAr: 'الرياضة',
        shortLabelEn: 'Gym',
        shortTime: '17:00 - 18:30',
        descriptionAr: 'تمرين القوة البدنية وتحرير الإندورفين.',
        descriptionEn: 'Physical workout and endorphin release.',
        icon: Dumbbell,
      },
      EVENING_SPRINT: {
        titleAr: 'العمل المسائي والمشاريع',
        titleEn: 'Evening Build Sprint',
        shortLabelAr: 'المساء',
        shortLabelEn: 'Evening',
        shortTime: '19:30 - 21:30',
        descriptionAr: 'حسم المشاريع الجانبية والتواصل المهني.',
        descriptionEn: 'Side projects, code backlog & communication.',
        icon: Laptop,
      },
      RETROSPECTIVE_CHECKIN: {
        titleAr: 'المراجعة وتفريغ الذهن',
        titleEn: 'Daily Retrospective',
        shortLabelAr: 'المراجعة',
        shortLabelEn: 'Review',
        shortTime: '21:30 - 22:30',
        descriptionAr: 'المحاسبة اليومية، فكرة اليوم، وسورة الملك.',
        descriptionEn: 'Daily wins, retrospective, and wind-down.',
        icon: Mic,
      },
      GRAND_REWARD_STATE: {
        titleAr: 'المكافأة والاحتفال بالإنجاز',
        titleEn: 'Grand Reward',
        shortLabelAr: 'المكافأة',
        shortLabelEn: 'Reward',
        shortTime: '22:30+',
        descriptionAr: 'متجر المكافآت الواقعية دون أدنى لوم.',
        descriptionEn: 'Guilt-free dopamine celebration.',
        icon: Trophy,
      },
    },
  },

  academic_student: {
    id: 'academic_student',
    titleAr: 'الطالب والباحث الأكاديمي',
    titleEn: 'Academic Student & Researcher',
    subtitleAr: 'للطلاب، الباحثين، وأصحاب الدراسات العليا: تنظيم المذاكرة والتحصيل والامتحانات.',
    subtitleEn: 'For students, postgrads and researchers mastering exams and papers.',
    badge: '🎓 تحصيل واستذكار',
    avatarEmoji: '🎓',
    stations: {
      COMMUTE_MORNING: {
        titleAr: 'ورد القرآن وصفاء الذهن',
        titleEn: 'Quran & Mental Clarity',
        shortLabelAr: 'القرآن',
        shortLabelEn: 'Quran',
        shortTime: '06:00 - 08:00',
        descriptionAr: 'بداية اليوم بنور القرآن لفتح مدارك الفهم والاستيعاب.',
        descriptionEn: 'Morning recitation for wisdom and mental focus.',
        icon: BookOpen,
      },
      WORK_MICRO_SPRINT: {
        titleAr: 'جلسات المذاكرة والتحصيل الأكاديمي',
        titleEn: 'Study & Lecture Mastery',
        shortLabelAr: 'المذاكرة',
        shortLabelEn: 'Study',
        shortTime: '09:00 - 13:00',
        descriptionAr: 'جلسات استذكار عميقة (بومودورو) لفهم أصعب المفاهيم.',
        descriptionEn: 'Intense study blocks for mastering complex subjects.',
        icon: GraduationCap,
      },
      ONE_SEC_FRICTION: {
        titleAr: 'كسر حاجز صعوبة المادة',
        titleEn: 'Study Anti-Procrastination',
        shortLabelAr: 'المقاومة',
        shortLabelEn: 'Friction',
        shortTime: '2 دقيقة',
        descriptionAr: 'تعهد دقيقتين لفتح الكتاب والبدء دون تردد.',
        descriptionEn: 'Open the book for 2 minutes to break friction.',
        icon: Sparkles,
      },
      SOCIAL_MEDIA_BREAK: {
        titleAr: 'راحة بصرية خالية من الشاشات',
        titleEn: 'Screen-Free Study Break',
        shortLabelAr: 'راحة',
        shortLabelEn: 'Break',
        shortTime: '15 دقيقة',
        descriptionAr: 'إراحة العين وتثبيت المعلومات بالاسترخاء.',
        descriptionEn: 'Rest your eyes and consolidate memory.',
        icon: Brain,
      },
      GYM_ANCHOR: {
        titleAr: 'تجديد الدورة الدموية والنشاط',
        titleEn: 'Brain Boost Movement',
        shortLabelAr: 'النشاط',
        shortLabelEn: 'Movement',
        shortTime: '16:30 - 18:00',
        descriptionAr: 'المشي أو الرياضة لضخ الأكسجين للدماغ وتنشيط الذاكرة.',
        descriptionEn: 'Exercise to oxygenate the brain and recharge memory.',
        icon: Dumbbell,
      },
      EVENING_SPRINT: {
        titleAr: 'مدارسة الأبحاث وحل المسائل',
        titleEn: 'Problem Solving & Research',
        shortLabelAr: 'المساء',
        shortLabelEn: 'Practice',
        shortTime: '19:00 - 21:00',
        descriptionAr: 'حل التمارين، تلخيص المراجع، وإعداد الأبحاث.',
        descriptionEn: 'Solving problem sets, thesis reading, paper writing.',
        icon: Laptop,
      },
      RETROSPECTIVE_CHECKIN: {
        titleAr: 'مراجعة الاستيعاب وتفريغ الذهن',
        titleEn: 'Knowledge Recall & Review',
        shortLabelAr: 'المراجعة',
        shortLabelEn: 'Recall',
        shortTime: '21:30 - 22:30',
        descriptionAr: 'سؤال اليوم: ماذا فهمت؟ + سورة الملك وأذكار النوم.',
        descriptionEn: 'Self-quizzing on key concepts + Surah Al-Mulk.',
        icon: Mic,
      },
      GRAND_REWARD_STATE: {
        titleAr: 'استراحة الإنجاز وتكريم النفس',
        titleEn: 'Study Celebration & Reward',
        shortLabelAr: 'المكافأة',
        shortLabelEn: 'Reward',
        shortTime: '22:30+',
        descriptionAr: 'كافئ نفسك على استيعابك بعشاء لذيذ أو جلسة مرحة.',
        descriptionEn: 'Celebrate your academic progress guilt-free.',
        icon: Trophy,
      },
    },
  },

  sharia_seeker: {
    id: 'sharia_seeker',
    titleAr: 'طالب العلم الشرعي والقرآن',
    titleEn: 'Sacred Knowledge Seeker',
    subtitleAr: 'لحفظة كتاب الله، طلاب الحلقات، والمهتمين بالعلوم الشرعية والتدبر.',
    subtitleEn: 'For Quran memorizers, Islamic students, and seekers of sacred knowledge.',
    badge: '🕌 حفظ وتدبر',
    avatarEmoji: '🕌',
    stations: {
      COMMUTE_MORNING: {
        titleAr: 'الورد القرآني وتثبيت الحفظ',
        titleEn: 'Quran Wird & Hifz Anchor',
        shortLabelAr: 'الورد',
        shortLabelEn: 'Quran',
        shortTime: 'بعد الفجر',
        descriptionAr: 'قراءة الزهراوين أو الورد اليومي مع التدبر الصباحي.',
        descriptionEn: 'Reciting Al-Zahrawayn or daily Juz with deep contemplation.',
        icon: BookOpen,
      },
      WORK_MICRO_SPRINT: {
        titleAr: 'مجالس الحفظ ومدارسة المتون',
        titleEn: 'Mutoon Memorization & Study',
        shortLabelAr: 'المتون',
        shortLabelEn: 'Texts',
        shortTime: 'الضحى والظهيرة',
        descriptionAr: 'حفظ المتون العلمية وشروح الأحاديث والفقه.',
        descriptionEn: 'Deep memorization and comprehension of classical texts.',
        icon: Scroll,
      },
      ONE_SEC_FRICTION: {
        titleAr: 'دفع الفتور وطلب الإعانة',
        titleEn: 'Renewing Intention & Resolve',
        shortLabelAr: 'النية',
        shortLabelEn: 'Resolve',
        shortTime: '2 دقيقة',
        descriptionAr: 'تجديد الإخلاص والاستعاذة من العجز والكسل.',
        descriptionEn: 'Renewing sincere intention and starting small.',
        icon: Sparkles,
      },
      SOCIAL_MEDIA_BREAK: {
        titleAr: 'خلوة الذكر والتفكر',
        titleEn: 'Contemplation & Dhikr',
        shortLabelAr: 'الخلوة',
        shortLabelEn: 'Dhikr',
        shortTime: '15 دقيقة',
        descriptionAr: 'صفاء القلب وتسبيح واستغفار لتثبيت العلم.',
        descriptionEn: 'Peaceful tasbih and mindful reflection.',
        icon: HeartHandshake,
      },
      GYM_ANCHOR: {
        titleAr: 'مرساة البدن والمؤمن القوي',
        titleEn: 'Strength & Physical Vitality',
        shortLabelAr: 'القوة',
        shortLabelEn: 'Strength',
        shortTime: 'العصر',
        descriptionAr: '«المؤمن القوي خير وأحب إلى الله من المؤمن الضعيف».',
        descriptionEn: 'Physical vitality to sustain long hours of study.',
        icon: Dumbbell,
      },
      EVENING_SPRINT: {
        titleAr: 'قراءة الشروح ومراجعة الأقران',
        titleEn: 'Commentaries & Peer Review',
        shortLabelAr: 'الشروح',
        shortLabelEn: 'Research',
        shortTime: 'المغرب والعشاء',
        descriptionAr: 'قراءة في كتب التفسير، الفقه، وتدوين الفوائد والشوارد.',
        descriptionEn: 'Reading commentaries and compiling gems of knowledge.',
        icon: Laptop,
      },
      RETROSPECTIVE_CHECKIN: {
        titleAr: 'محاسبة النفس وصلاة الوتر',
        titleEn: 'Self-Audit & Witr Prayer',
        shortLabelAr: 'المحاسبة',
        shortLabelEn: 'Account',
        shortTime: 'قبل النوم',
        descriptionAr: 'حاسبوا أنفسكم قبل أن تحاسبوا + سورة الملك وركعات الوتر.',
        descriptionEn: 'Nightly self-reckoning, Surah Al-Mulk, and Witr prayer.',
        icon: Mic,
      },
      GRAND_REWARD_STATE: {
        titleAr: 'بركة اليوم والراحة المستحقة',
        titleEn: 'Sacred Rest & Leisure',
        shortLabelAr: 'المكافأة',
        shortLabelEn: 'Reward',
        shortTime: 'الليل',
        descriptionAr: 'الترويح عن النفس المباح لاستئناف النشاط غداً.',
        descriptionEn: 'Mindful relaxation to recharge for tomorrow\'s seeking.',
        icon: Trophy,
      },
    },
  },

  freelancer_creator: {
    id: 'freelancer_creator',
    titleAr: 'المستقل وصانع المحتوى',
    titleEn: 'Freelancer & Content Creator',
    subtitleAr: 'للمستقلين، المصممين، الكُتّاب، وصُنّاع المحتوى أصحاب المواعيد الحرة.',
    subtitleEn: 'For freelancers, creators, writers, and designers managing agile flows.',
    badge: '🎨 إبداع وحرية',
    avatarEmoji: '🎨',
    stations: {
      COMMUTE_MORNING: {
        titleAr: 'ورد الإلهام وسكينة الصباح',
        titleEn: 'Morning Inspiration & Wird',
        shortLabelAr: 'الإلهام',
        shortLabelEn: 'Inspire',
        shortTime: '06:30 - 08:30',
        descriptionAr: 'صفاء روحي وقرآني يملأ الوجدان بالأفكار البكر.',
        descriptionEn: 'Spiritual grounding for high-level creative ideation.',
        icon: BookOpen,
      },
      WORK_MICRO_SPRINT: {
        titleAr: 'جلسات التدفق الإبداعي والإنتاج',
        titleEn: 'Creative Flow Sprints',
        shortLabelAr: 'الإبداع',
        shortLabelEn: 'Create',
        shortTime: '09:00 - 13:00',
        descriptionAr: 'جلسات كتابة، تصميم، مونتاج، أو بناء بدون أي مقاطعات.',
        descriptionEn: 'Deep creative flow: writing, editing, designing.',
        icon: Palette,
      },
      ONE_SEC_FRICTION: {
        titleAr: 'كسر متلازمة الصفحة البيضاء',
        titleEn: 'Blank Page Friction Buster',
        shortLabelAr: 'البدء',
        shortLabelEn: 'Friction',
        shortTime: '2 دقيقة',
        descriptionAr: 'ابدأ بكتابة مسودة أولى سيئة خلال 120 ثانية فقط.',
        descriptionEn: 'Write a messy first sentence to break resistance.',
        icon: Sparkles,
      },
      SOCIAL_MEDIA_BREAK: {
        titleAr: 'استراحة حسية وتجديد الشغف',
        titleEn: 'Sensory Reset Break',
        shortLabelAr: 'شغف',
        shortLabelEn: 'Reset',
        shortTime: '15 دقيقة',
        descriptionAr: 'تغذية بصرية خفيفة أو فنجان قهوة لتجديد الأفكار.',
        descriptionEn: 'Coffee and visual nourishment to refresh ideas.',
        icon: Brain,
      },
      GYM_ANCHOR: {
        titleAr: 'تفريغ التوتر وتنشيط الجسد',
        titleEn: 'Body Reset & Fitness',
        shortLabelAr: 'الحركة',
        shortLabelEn: 'Movement',
        shortTime: '16:00 - 17:30',
        descriptionAr: 'الخروج من كرسي المكتب وتنشيط عضلات الظهر والجسم.',
        descriptionEn: 'Step away from the desk and release posture tension.',
        icon: Dumbbell,
      },
      EVENING_SPRINT: {
        titleAr: 'تسليم المشاريع وتواصل العملاء',
        titleEn: 'Client Pipeline & Delivery',
        shortLabelAr: 'المشاريع',
        shortLabelEn: 'Pipeline',
        shortTime: '18:30 - 20:30',
        descriptionAr: 'التواصل مع العملاء، إرسال العروض، وتنسيق التسليمات.',
        descriptionEn: 'Outreach, proposals, deliverables, and invoices.',
        icon: Laptop,
      },
      RETROSPECTIVE_CHECKIN: {
        titleAr: 'مراجعة المخرجات وتفريغ الأفكار',
        titleEn: 'Creative Day Retrospective',
        shortLabelAr: 'التفريغ',
        shortLabelEn: 'Brain Dump',
        shortTime: '21:00 - 22:00',
        descriptionAr: 'تدوين فكرة اليوم الذهبية وتفريغ مسودات الغد.',
        descriptionEn: 'Capture today\'s breakthrough idea and clear your mind.',
        icon: Mic,
      },
      GRAND_REWARD_STATE: {
        titleAr: 'مكافأة الإبداع والمتعة',
        titleEn: 'Creator Dopamine Reward',
        shortLabelAr: 'المكافأة',
        shortLabelEn: 'Reward',
        shortTime: '22:00+',
        descriptionAr: 'استمتع بكتاب كنت تنتظره أو فيلم ممتع دون أي عمل.',
        descriptionEn: 'Enjoy high-quality leisure to refuel your muse.',
        icon: Trophy,
      },
    },
  },

  flexible_home: {
    id: 'flexible_home',
    titleAr: 'تنظيم الحياة المرنة ورب الأسرة',
    titleEn: 'Life Harmonizer & Homemaker',
    subtitleAr: 'لمن لا يرتبط بوظيفة رسمية: تنظيم أهداف البيت، العائلة، القراءة، والعافية الشخصية.',
    subtitleEn: 'For homemakers, retirees, and individuals designing life on their own terms.',
    badge: '🏡 حياة متزنة',
    avatarEmoji: '🏡',
    stations: {
      COMMUTE_MORNING: {
        titleAr: 'سكينة الصباح والورد القرآني',
        titleEn: 'Morning Serenity & Quran',
        shortLabelAr: 'السكينة',
        shortLabelEn: 'Peace',
        shortTime: '06:00 - 08:30',
        descriptionAr: 'هدوء البيت الصباحي مع القرآن الكريم وأذكار اليوم.',
        descriptionEn: 'Quiet morning reflection, Quran Wird, and gratitude.',
        icon: BookOpen,
      },
      WORK_MICRO_SPRINT: {
        titleAr: 'المشاريع المنزلية والشخصية',
        titleEn: 'Home & Personal Projects',
        shortLabelAr: 'البيت',
        shortLabelEn: 'Projects',
        shortTime: '09:00 - 12:30',
        descriptionAr: 'ترتيب الأولويات، مهام الأسرة، وإنجاز مشاريع المنزل.',
        descriptionEn: 'Family priorities, home projects, organizing routines.',
        icon: Home,
      },
      ONE_SEC_FRICTION: {
        titleAr: 'كسر ثقل البداية في المهام',
        titleEn: 'Gentle Anti-Procrastination',
        shortLabelAr: 'البدء',
        shortLabelEn: 'Gentle',
        shortTime: '2 دقيقة',
        descriptionAr: 'ابدأ بترتيب مساحة صغيرة فقط لدقيقتين دون تعقيد.',
        descriptionEn: 'Tackle one tiny corner for 2 minutes to gain momentum.',
        icon: Sparkles,
      },
      SOCIAL_MEDIA_BREAK: {
        titleAr: 'شاي الصباح والهدوء النفسي',
        titleEn: 'Morning Tea & Mindfulness',
        shortLabelAr: 'استرخاء',
        shortLabelEn: 'Tea Break',
        shortTime: '15 دقيقة',
        descriptionAr: 'لحظة صمت وتلذذ بفنجانك المفضل بعيداً عن الهاتف.',
        descriptionEn: 'Savor a warm drink and quiet your thoughts.',
        icon: Brain,
      },
      GYM_ANCHOR: {
        titleAr: 'المشي ونشاط العافية والصحة',
        titleEn: 'Wellness Walk & Movement',
        shortLabelAr: 'العافية',
        shortLabelEn: 'Wellness',
        shortTime: '16:00 - 17:30',
        descriptionAr: 'مشي خفيف في الهواء الطلق أو تمارين تمدد لطيفة.',
        descriptionEn: 'Outdoor walk, light stretching, and vitality.',
        icon: Dumbbell,
      },
      EVENING_SPRINT: {
        titleAr: 'القراءة الحرة وتطوير المهارات',
        titleEn: 'Reading & Skill Cultivation',
        shortLabelAr: 'القراءة',
        shortLabelEn: 'Reading',
        shortTime: '18:30 - 20:30',
        descriptionAr: 'قراءة كتاب ملهم، تعلم مهارة جديدة، أو ممارسة هواية.',
        descriptionEn: 'Inspiring reading, craft hobbies, and personal learning.',
        icon: BookOpen,
      },
      RETROSPECTIVE_CHECKIN: {
        titleAr: 'سكينة المساء والامتنان',
        titleEn: 'Evening Gratitude & Peace',
        shortLabelAr: 'الامتنان',
        shortLabelEn: 'Gratitude',
        shortTime: '21:00 - 22:00',
        descriptionAr: 'تدوين نِعَم اليوم، سورة الملك، والاستعداد للنوم.',
        descriptionEn: 'Counting today\'s blessings and quiet evening wind-down.',
        icon: Mic,
      },
      GRAND_REWARD_STATE: {
        titleAr: 'واحة الراحة والاستمتاع الذاتي',
        titleEn: 'Guilt-Free Leisure Sanctuary',
        shortLabelAr: 'الراحة',
        shortLabelEn: 'Leisure',
        shortTime: '22:00+',
        descriptionAr: 'استرخاء كامل وعناية بالنفس دون أدنى تأنيب ضمير.',
        descriptionEn: 'Pure peaceful self-care without any guilt.',
        icon: Trophy,
      },
    },
  },

  custom: {
    id: 'custom',
    titleAr: 'مخصص بالكامل',
    titleEn: 'Custom Blueprint',
    subtitleAr: 'حرية مطلقة في تعيين كل محطة واسمها وهدفها وفق يومك الفريد.',
    subtitleEn: 'Total freedom to customize every station to your exact rhythm.',
    badge: '🛠️ صياغتك الذاتية',
    avatarEmoji: '⚙️',
    stations: {
      COMMUTE_MORNING: {
        titleAr: 'المحطة الأولى: انطلاقة اليوم',
        titleEn: 'Station 1: Daily Launch',
        shortLabelAr: 'المحطة 1',
        shortLabelEn: 'Station 1',
        shortTime: 'الصباح',
        descriptionAr: 'بداية اليوم والورد المفضل.',
        descriptionEn: 'Start your day with your chosen anchor.',
        icon: Compass,
      },
      WORK_MICRO_SPRINT: {
        titleAr: 'المحطة الثانية: التركيز الأول',
        titleEn: 'Station 2: Primary Focus',
        shortLabelAr: 'المحطة 2',
        shortLabelEn: 'Station 2',
        shortTime: 'النهار',
        descriptionAr: 'أهم هدف في نهارك.',
        descriptionEn: 'Your primary daytime objective.',
        icon: Briefcase,
      },
      ONE_SEC_FRICTION: {
        titleAr: 'المحطة: كسر المقاومة',
        titleEn: 'Friction Breaker',
        shortLabelAr: 'البدء',
        shortLabelEn: 'Start',
        shortTime: '2 دقيقة',
        descriptionAr: 'قاعدة الدقيقتين للبدء.',
        descriptionEn: '2-minute anti-friction trigger.',
        icon: Sparkles,
      },
      SOCIAL_MEDIA_BREAK: {
        titleAr: 'المحطة: استراحة ذهنية',
        titleEn: 'Mindful Break',
        shortLabelAr: 'استراحة',
        shortLabelEn: 'Break',
        shortTime: '15 دقيقة',
        descriptionAr: 'فصل وتجديد نشاط.',
        descriptionEn: 'Rest and recharge.',
        icon: Brain,
      },
      GYM_ANCHOR: {
        titleAr: 'المحطة الثالثة: النشاط والبدن',
        titleEn: 'Station 3: Physical Vitality',
        shortLabelAr: 'المحطة 3',
        shortLabelEn: 'Station 3',
        shortTime: 'العصر',
        descriptionAr: 'الحركة والرياضة والعافية.',
        descriptionEn: 'Movement, health and vitality.',
        icon: Dumbbell,
      },
      EVENING_SPRINT: {
        titleAr: 'المحطة الرابعة: استثمار المساء',
        titleEn: 'Station 4: Evening Priority',
        shortLabelAr: 'المحطة 4',
        shortLabelEn: 'Station 4',
        shortTime: 'المساء',
        descriptionAr: 'الهدف الثانوي أو التفرغ للمشاريع.',
        descriptionEn: 'Evening focus and personal projects.',
        icon: Laptop,
      },
      RETROSPECTIVE_CHECKIN: {
        titleAr: 'المحطة الخامسة: مراجعة اليوم',
        titleEn: 'Station 5: Evening Reflection',
        shortLabelAr: 'المحطة 5',
        shortLabelEn: 'Station 5',
        shortTime: 'الليل',
        descriptionAr: 'تقييم اليوم وتفريغ الذهن.',
        descriptionEn: 'Review wins and clear your thoughts.',
        icon: Mic,
      },
      GRAND_REWARD_STATE: {
        titleAr: 'المحطة السادسة: المكافأة والاسترخاء',
        titleEn: 'Station 6: Grand Reward',
        shortLabelAr: 'المكافأة',
        shortLabelEn: 'Reward',
        shortTime: 'وقت النوم',
        descriptionAr: 'الاستمتاع بثمرة يومك.',
        descriptionEn: 'Guilt-free relaxation.',
        icon: Trophy,
      },
    },
  },
};

/**
 * Resolves station metadata combining persona preset and user custom overrides
 */
export function resolveStationMetadata(
  stationId: StationId,
  personaId: LifestylePersonaId = 'builder_exec',
  overrides?: Partial<Record<StationId, StationCustomOverride>>,
  _isAr = true
): StationMetadata {
  if (stationId === 'HOME') {
    return {
      id: 'HOME',
      stepNum: 0,
      titleAr: 'الرئيسية • لوحة اليوم',
      titleEn: 'Home Dashboard',
      shortLabelAr: 'الرئيسية',
      shortLabelEn: 'Home',
      shortTime: 'نظرة اليوم والتحفيز',
      descriptionAr: 'لوحة الانطلاقة والتحفيز ومواقيت الصلاة الحية ومسار اليوم',
      descriptionEn: 'Daily overview, motivational spark, and real-time prayer schedule',
      icon: Home,
    };
  }

  const persona = LIFESTYLE_PERSONAS[personaId] || LIFESTYLE_PERSONAS.builder_exec;
  const base = persona.stations[stationId] || LIFESTYLE_PERSONAS.builder_exec.stations[stationId];
  const override = overrides?.[stationId];

  // Map step numbers
  const stepNums: Record<StationId, number> = {
    HOME: 0,
    COMMUTE_MORNING: 1,
    WORK_MICRO_SPRINT: 2,
    ONE_SEC_FRICTION: 0,
    SOCIAL_MEDIA_BREAK: 0,
    GYM_ANCHOR: 3,
    EVENING_SPRINT: 4,
    RETROSPECTIVE_CHECKIN: 5,
    GRAND_REWARD_STATE: 6,
  };

  return {
    id: stationId,
    stepNum: stepNums[stationId] || 1,
    titleAr: override?.customTitle || base.titleAr,
    titleEn: override?.customTitle || base.titleEn,
    shortLabelAr: override?.customShortLabel || base.shortLabelAr,
    shortLabelEn: override?.customShortLabel || base.shortLabelEn,
    shortTime: override?.customSubtitle || base.shortTime,
    descriptionAr: base.descriptionAr,
    descriptionEn: base.descriptionEn,
    icon: base.icon,
  };
}

export const PERSONA_CONFIGS = LIFESTYLE_PERSONAS;
